# Generated by Django 4.2.2 on 2023-06-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_model1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model2',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AddField(
            model_name='model2',
            name='pole3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
