# Generated by Django 4.2.2 on 2023-06-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_model2_options_model2_pole3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole1', models.IntegerField()),
                ('pole2', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
    ]
